@startuml
class GameManager {
    + {static} Instance : GameManager <<get>>
    - gameModeOverride : ParticipantGroup
    + {static} CurrentGameMode : ParticipantGroup <<get>>
    - scoreText : Text
    - crunchSound : AudioClip
    - playerController : ToadController
    - speedIncreasePerPoint : float = 0.1f
    - _score : int
    - Awake() : void
    - Start() : void
    - WaitForFirebaseGroupAssignment() : System.Collections.IEnumerator
    - SetGameMode(group:ParticipantGroup) : void
    + IncrementScore() : void
    - UpdateScoreDisplay() : void
}
enum ParticipantGroup {
    NoOverride= 0,
    TestGroup1Text= 1,
    TestGroup2Arrows= 2,
    ControlGroupBlank= 3,
}
MonoBehaviour <|-- GameManager
GameManager +-- ParticipantGroup
@enduml
