@startuml
class ImageFlasher {
    + {static} Instance : ImageFlasher <<get>>
    - carTextToFlash : RawImage
    - carArrowToFlash : RawImage
    - stormTextToFlash : RawImage
    - stormArrowToFlash : RawImage
    - whiteImg : RawImage
    - blackImg : RawImage
    - scoreText : Text
    - flashDuration : float = 0.033f
    - _flashWait : WaitForSecondsRealtime
    - _currentFlashCoroutine : Coroutine
    - Awake() : void
    - DisableImageState() : void
    + TriggerCarFlash() : void
    + TriggerStormFlash() : void
    - HandleCarFlash() : IEnumerator
    - HandleStormFlash() : IEnumerator
    - FadeImageAlpha(image:RawImage, startAlpha:float, endAlpha:float, frameCount:int) : IEnumerator
}
class CoroutineUtils <<static>> {
    + {static} WaitForFrames(frames:int) : IEnumerator
}
MonoBehaviour <|-- ImageFlasher
@enduml
