@startuml
class Lightning {
    - thunderCrackSound : AudioClip
    - destroyDistanceBehindPlayer : float = 50.0f
    - playerTransform : Transform
    - Update() : void
    - OnTriggerEnter(other:Collider) : void
}
MonoBehaviour <|-- Lightning
@enduml
