@startuml
class MainMenu {
    - mainPanel : GameObject
    - sourcesPanel : GameObject
    - Start() : void
    + GoToMain() : void
    + GoToSources() : void
    + OnPlayClicked() : void
}
MonoBehaviour <|-- MainMenu
@enduml
