@startuml
class TextureScroller {
    - scrollSpeedX : float
    - scrollSpeedY : float
    - meshRenderer : MeshRenderer
    - offsetX : float
    - offsetY : float
    - Awake() : void
    - Update() : void
}
MonoBehaviour <|-- TextureScroller
@enduml
